CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                                                       "MigrationId" character varying(150) NOT NULL,
                                                       "ProductVersion" character varying(32) NOT NULL,
                                                       CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Tasks" (
                         "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                         "Title" text NOT NULL,
                         "IsCompleted" boolean NOT NULL,
                         "IsDeleted" boolean NOT NULL,
                         "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241111213003_InitialCreate', '8.0.10');

COMMIT;
